logging:
  config: classpath:logback/logback-@spring.profiles.active@.xml

spring:
  application:
    name: DC
  profiles:
    #active: @spring.profiles.active@
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL

  jackson:
    default-property-inclusion: non_null

mybatis:
  mapper-locations: mapper/**/*.xml