spring:
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/iotdb?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 650312

server:
  port: 8082

mqtt:
  host: tcp://8.140.106.126:1883
  username: root
  password: Aa-654321
