#logging:
#  level:
#    com.iot.mapper: debug

spring:
  resources:
    static-locations: file:D:/data/backgroundImage/

  datasource:
    url: jdbc:mysql://192.168.1.9:3306/iotdb?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 650312
#    url: jdbc:mysql://172.16.2.246:13306/iotdb?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
#    username: dhub_dev
#    password: 123456

mqtt:
  host: tcp://9.140.106.126:1883
  username: root
  password: Aa-654321
  resource:
    topic: D:/data/mqtt/topic.ini

upload:
  path: D:/data/backgroundImage/
