logging:
  com.iot.mapper: debug

spring:
  resources:
    static-locations: file:/data/backgroundImage/

  datasource:
    url: jdbc:mysql://8.140.106.126:3306/iotdb?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

mqtt:
  host: tcp://8.140.106.126:1883
  username: root
  password: Aa-654321

upload:
  path: /data/backgroundImage/