logging:
  file:
    path: /opt/lot/logs

spring:
  datasource:
    url: jdbc:mysql://8.140.106.126:3306/lotdb?useSSL=false&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: 123456

mqtt:
  host: tcp://8.140.106.126:1883
  username: root
  password: Aa-654321